# .streamlit/secrets.toml

[passwords]
"daniel.maroso" = "bc736d528a4c2ffcc600d57e5945fb25e3377e65c9ac2e9d60622ae04e9ddcfc"
"maria.maroso" = "87f11321d893e6f2ecb6b89b94546dd64d203b395bf3c6606868930b73ddcca6"
